export const AUDIENCES = [
  { slug: 'corretores', name: 'Corretores', singular: 'corretor', description: 'Profissionais que conciliam captação, divulgação, atendimento e negociação em uma rotina própria.', existingPath: '/corretor-autonomo/' },
  { slug: 'imobiliarias', name: 'Imobiliárias', singular: 'imobiliária', description: 'Operações com carteira de imóveis e equipe comercial que precisam conectar canais, distribuição de contatos e acompanhamento.', existingPath: '/imobiliarias/' },
  { slug: 'incorporadoras', name: 'Incorporadoras', singular: 'incorporadora', description: 'Empresas que desenvolvem, lançam e vendem empreendimentos, articulando produto, campanha e parceiros comerciais.', existingPath: '/construtoras-incorporadoras/' },
  { slug: 'empreiteiras', name: 'Empreiteiras', singular: 'empreiteira', description: 'Empresas que buscam contratos de execução de obras e parcerias B2B, com foco em capacidade técnica e adequação ao projeto.', existingPath: null },
  { slug: 'construtoras', name: 'Construtoras', singular: 'construtora', description: 'Empresas de construção cujo objetivo pode ser contratar obras ou comercializar produtos próprios, conforme o modelo de negócio a validar.', existingPath: null },
];

export const SERVICES = [
  {
    slug: 'agencia-de-marketing-imobiliario',
    name: 'Agência de marketing imobiliário',
    keyword: 'agência de marketing imobiliário',
    shortName: 'Marketing imobiliário',
    eyebrow: 'Estratégia e operação comercial',
    headline: 'Marketing imobiliário conectado ao que sua operação consegue atender.',
    intro: 'Quem procura uma agência de marketing imobiliário precisa entender onde a comunicação encontra a venda: oferta, canais, atendimento e acompanhamento. Comece pelo diagnóstico atual da Imobiturbo para mapear seu cenário e discutir o formato de apoio adequado.',
    problem: 'Divulgar sem uma prioridade comercial definida espalha esforço. Uma carteira ampla, um lançamento e uma empresa de obras exigem mensagens e jornadas diferentes. Quando o contato chega sem contexto ou responsável, fica difícil distinguir um problema de aquisição de uma falha no atendimento.',
    steps: [
      { title: 'Entender o negócio', text: 'Identificar o que está sendo vendido, para quem, em qual estágio e com qual capacidade de atendimento. A leitura inclui canais existentes e obstáculos da rotina comercial.' },
      { title: 'Escolher a prioridade', text: 'Separar necessidades de posicionamento, página, mídia e conteúdo. Definir qual frente merece atenção primeiro e quais informações faltam para decidir.' },
      { title: 'Conectar a jornada', text: 'Relacionar mensagem, ponto de contato, qualificação e próximo passo. Estabelecer o papel da equipe e dos parceiros para que a divulgação tenha continuidade comercial.' },
      { title: 'Discutir o escopo', text: 'Usar o diagnóstico para avaliar prioridades, responsabilidades e formato de acompanhamento. A execução de cada frente depende do escopo que vier a ser acordado.' },
    ],
    deliverables: [
      'Mapa de oferta, público e objetivo para orientar a discussão de escopo.',
      'Leitura dos canais atuais e das lacunas entre divulgação e atendimento.',
      'Prioridades de posicionamento e comunicação a avaliar no projeto.',
      'Desenho da jornada entre interesse, qualificação e conversa comercial.',
      'Critérios de acompanhamento e responsabilidades a definir com a operação.',
      'Lista de informações e materiais necessários para planejar as próximas ações.',
    ],
    faq: [
      { question: 'A Imobiturbo funciona como uma agência de marketing imobiliário?', answer: 'A Imobiturbo conecta diagnóstico, orientação comercial e tecnologia. A busca por uma agência pode envolver necessidades diferentes; a conversa inicial identifica se o cenário pede consultoria, organização da operação ou uma frente específica, cujo escopo precisa ser confirmado.' },
      { question: 'O diagnóstico inclui gestão mensal de todos os canais?', answer: 'O diagnóstico é o ponto de partida para entender a operação. Gestão de anúncios, produção de conteúdo, desenvolvimento de páginas e acompanhamento recorrente precisam ser discutidos e acordados; não estão automaticamente incluídos.' },
      { question: 'Como saber se preciso de marketing ou de processo comercial?', answer: 'Observe onde a jornada trava. Ausência de procura, mensagem pouco clara, contatos sem perfil e oportunidades sem retorno são problemas distintos. Leve ao diagnóstico exemplos de campanhas e atendimentos para localizar a prioridade.' },
      { question: 'Como começar a conversa?', answer: 'Acesse o diagnóstico atual e descreva seu público, sua oferta e o principal gargalo. Essas informações ajudam a discutir os próximos passos sem presumir um pacote único.' },
    ],
    profiles: {
      corretores: {
        headline: 'Marketing para o corretor que também precisa atender e negociar.',
        intro: 'Escolher um segmento e uma oferta facilita a divulgação e o acompanhamento das conversas. O diagnóstico considera a rotina individual antes de sugerir novas frentes de trabalho.',
        pain: 'Publicar imóveis de perfis muito diferentes e responder a todas as conversas sozinho pode deixar a comunicação dispersa e os retornos pendentes.',
        focus: ['Recorte de carteira e perfil de comprador.', 'Mensagem ligada à atuação e aos imóveis disponíveis.', 'Rotina de resposta e acompanhamento compatível com a agenda.'],
        faq: { question: 'Preciso atuar em vários canais ao mesmo tempo?', answer: 'A escolha depende de onde seu público procura imóveis e de quanto tempo você tem para atender. O diagnóstico ajuda a priorizar uma jornada que caiba na rotina, antes de ampliar canais.' },
      },
      imobiliarias: {
        headline: 'Marketing para a imobiliária com carteira, equipe e responsabilidades claras.',
        intro: 'A comunicação da marca precisa conversar com as prioridades da carteira e com o padrão de atendimento do time. Leve ao diagnóstico como os contatos são distribuídos e acompanhados.',
        pain: 'Cada corretor divulgar e atender de um jeito dificulta a leitura do que veio da marca, de qual oferta despertou interesse e de quem deve conduzir a oportunidade.',
        focus: ['Prioridades por carteira e objetivo comercial.', 'Coerência entre marca e divulgação dos corretores.', 'Distribuição de contatos e critérios de acompanhamento.'],
        faq: { question: 'O trabalho substitui a gestão dos corretores?', answer: 'A divulgação depende da continuidade do atendimento. A gestão da equipe e as responsabilidades comerciais devem entrar na discussão de escopo para que marketing e rotina do time estejam alinhados.' },
      },
      incorporadoras: {
        headline: 'Marketing para conectar empreendimento, fase comercial e rede de parceiros.',
        intro: 'Uma incorporadora precisa comunicar o produto de acordo com a fase de lançamento e venda. O diagnóstico examina narrativa, canais próprios e participação de corretores e imobiliárias parceiras.',
        pain: 'Campanha, material do empreendimento e discurso dos parceiros podem apresentar informações diferentes e fragmentar a jornada do comprador.',
        focus: ['Posicionamento do empreendimento e estágio de comercialização.', 'Informações do produto aprovadas para divulgação.', 'Coordenação entre campanha e parceiros comerciais.'],
        faq: { question: 'É possível discutir um empreendimento já em vendas?', answer: 'Sim. Leve ao diagnóstico a fase comercial, as unidades disponíveis, os canais e as principais objeções. A conversa deve considerar o estoque atual e a operação existente antes de definir prioridades.' },
      },
      empreiteiras: {
        headline: 'Marketing para apresentar capacidade de obra e abrir conversas B2B.',
        intro: 'Para uma empreiteira, a oferta costuma ser a execução de obras. A comunicação deve ajudar contratantes e parceiros a entender especialidades, capacidade e critérios de contratação.',
        pain: 'Uma divulgação centrada em compradores de imóveis atrai demandas inadequadas quando a empresa vende execução de obra e não possui produto imobiliário para comercializar.',
        focus: ['Especialidades e tipos de obra que a empresa executa.', 'Credenciais e evidências técnicas verificáveis.', 'Jornada para contratação e parcerias B2B.'],
        faq: { question: 'Uma empreiteira deve anunciar imóveis?', answer: 'Somente se houver um produto imobiliário que ela esteja autorizada a comercializar. Para contratação de obras, o diagnóstico deve partir do serviço técnico, do perfil do contratante e das parcerias desejadas.' },
      },
      construtoras: {
        headline: 'Marketing para a construtora a partir do seu modelo de negócio.',
        intro: 'Antes de escolher canais, é necessário esclarecer se a construtora busca contratos de obra, vende produtos próprios ou atua nas duas frentes. O diagnóstico parte dessa distinção.',
        pain: 'Misturar execução de obra e venda de unidades na mesma mensagem dificulta entender a oferta e encaminhar cada interessado ao responsável correto.',
        focus: ['Validação do objetivo: obras ou produtos próprios.', 'Mensagens específicas para cada oferta confirmada.', 'Critérios de encaminhamento para atendimento técnico ou comercial.'],
        faq: { question: 'A estratégia de uma construtora é igual à de uma incorporadora?', answer: 'Depende da atividade. Venda de empreendimento próprio e contratação de obra têm públicos e decisões diferentes. O diagnóstico valida o papel da empresa em cada oferta antes de discutir a comunicação.' },
      },
    },
  },
  {
    slug: 'landing-pages-imobiliarias',
    name: 'Landing pages imobiliárias',
    keyword: 'landing pages imobiliárias',
    shortName: 'Landing pages',
    eyebrow: 'Oferta e jornada de contato',
    headline: 'Landing pages imobiliárias com uma oferta clara e um próximo passo definido.',
    intro: 'Uma landing page reúne as informações necessárias para uma decisão específica: conhecer um imóvel, conversar sobre um empreendimento ou solicitar avaliação de uma obra. Use o diagnóstico atual da Imobiturbo para entender qual jornada sua operação precisa antes de discutir a criação de uma página.',
    problem: 'Enviar pessoas para uma página genérica pode esconder a oferta que motivou o clique. Informações incompletas, formulários sem propósito e contatos sem destino definido criam dúvidas para o visitante e trabalho adicional para quem atende.',
    steps: [
      { title: 'Definir a decisão', text: 'Escolher uma oferta e o próximo passo esperado. Uma visita a imóvel, uma conversa sobre lançamento e um pedido de proposta de obra precisam de conteúdos e perguntas diferentes.' },
      { title: 'Organizar o conteúdo', text: 'Reunir informações verificadas, imagens autorizadas, condições atualizadas e respostas às dúvidas relevantes. Identificar o que ainda depende de aprovação antes da publicação.' },
      { title: 'Planejar o contato', text: 'Definir quais dados são necessários, quem recebe a solicitação e como a origem acompanha o atendimento. Avaliar a experiência de leitura e contato no celular.' },
      { title: 'Avaliar a implementação', text: 'Discutir desenvolvimento, integrações, manutenção e critérios de acompanhamento conforme a necessidade identificada. Publicação e suporte dependem de um escopo confirmado.' },
    ],
    deliverables: [
      'Definição de oferta, público e ação principal da página a planejar.',
      'Roteiro de conteúdo com dúvidas e informações necessárias à decisão.',
      'Inventário de imagens, dados e autorizações pendentes.',
      'Requisitos do formulário ou contato por WhatsApp a avaliar.',
      'Plano de encaminhamento e identificação da origem dos contatos.',
      'Critérios de revisão de conteúdo, uso no celular e atualização da oferta.',
    ],
    faq: [
      { question: 'Uma landing page substitui o site da empresa?', answer: 'Ela pode atender uma oferta específica, enquanto o site reúne informações mais amplas sobre a operação. A escolha depende da jornada: o visitante deve encontrar o que procura e compreender qual é o próximo passo.' },
      { question: 'A página pode encaminhar contatos para o WhatsApp?', answer: 'Esse caminho pode ser avaliado, assim como formulários e integrações. É necessário definir número, responsável, dados úteis e continuidade do atendimento antes de confirmar a implementação.' },
      { question: 'Quais materiais preciso levar ao diagnóstico?', answer: 'Leve a oferta, o público pretendido, imagens autorizadas, informações comerciais atualizadas e exemplos das dúvidas recebidas. Para obras, inclua especialidades, área de atendimento e requisitos para avaliar uma solicitação.' },
      { question: 'Uma landing page garante contatos ou posição no Google?', answer: 'Não. Procura, distribuição, conteúdo, concorrência e atendimento influenciam a jornada. O diagnóstico ajuda a discutir o papel da página e o escopo necessário, sem garantia de volume ou posicionamento.' },
    ],
    profiles: {
      corretores: {
        headline: 'Uma página para apresentar o imóvel ou recorte de carteira do corretor.',
        intro: 'A página pode reunir o contexto que se perde em conversas e links dispersos. O diagnóstico ajuda a escolher entre destacar um imóvel ou organizar uma oferta de atuação mais específica.',
        pain: 'O interessado pede repetidamente as mesmas informações quando fotos, características e condições estão espalhadas e desatualizadas.',
        focus: ['Informações atuais e autorização de divulgação do imóvel.', 'Dúvidas que antecedem uma conversa ou visita.', 'Contato identificado e próximo passo conduzido pelo corretor.'],
        faq: { question: 'Preciso de uma página para cada imóvel?', answer: 'Não necessariamente. A decisão considera duração da oferta, características da carteira e forma de divulgação. Uma página por imóvel exige atualização quando a disponibilidade ou as condições mudam.' },
      },
      imobiliarias: {
        headline: 'Landing pages para ofertas da carteira com atendimento definido.',
        intro: 'Uma imobiliária pode precisar de páginas para uma seleção de imóveis, captação de proprietários ou campanhas específicas. Cada objetivo exige uma mensagem e um encaminhamento próprios.',
        pain: 'Usar o mesmo formulário para proprietários e compradores dificulta a qualificação e a distribuição das solicitações para a equipe.',
        focus: ['Separação das jornadas de comprador e proprietário.', 'Atualização de disponibilidade e informações da carteira.', 'Destino dos contatos e identificação da campanha.'],
        faq: { question: 'A página já vem integrada ao sistema da imobiliária?', answer: 'Integrações precisam ser avaliadas conforme o sistema e o fluxo existente. Leve ao diagnóstico como a equipe recebe contatos hoje para discutir requisitos e responsabilidades de implementação.' },
      },
      incorporadoras: {
        headline: 'Landing pages para explicar o empreendimento e sua fase comercial.',
        intro: 'A apresentação de um empreendimento deve organizar conceito, tipologias e informações aprovadas para o estágio atual. O contato precisa preservar qual produto e canal motivaram o interesse.',
        pain: 'Materiais de fases distintas e condições antigas podem circular junto da campanha atual, gerando expectativas que o atendimento precisa corrigir.',
        focus: ['Conteúdo aprovado para a fase do empreendimento.', 'Tipologias e informações comerciais verificadas.', 'Encaminhamento para equipe ou parceiro responsável.'],
        faq: { question: 'É possível planejar a página antes do lançamento?', answer: 'Sim, desde que o objetivo e os materiais permitidos nessa fase sejam definidos. O diagnóstico deve identificar o que pode ser divulgado, quem aprova o conteúdo e qual contato a operação está pronta para atender.' },
      },
      empreiteiras: {
        headline: 'Uma página para qualificar pedidos de obra e conversas com parceiros.',
        intro: 'A landing page de uma empreiteira deve explicar serviços, especialidades e informações necessárias para avaliar uma contratação. O objetivo é encaminhar uma demanda de obra com contexto técnico.',
        pain: 'Pedidos sem tipo de obra, escopo ou localização exigem várias trocas antes de a empresa saber se pode atender.',
        focus: ['Serviços e limites de atuação da empreiteira.', 'Dados iniciais de escopo, local e fase da obra.', 'Contato para contratação técnica e parcerias B2B.'],
        faq: { question: 'O formulário pode fornecer um orçamento imediato?', answer: 'Preço e prazo de obra dependem de informações e avaliação técnica. A página pode orientar o envio dos dados iniciais; qualquer orçamento exige análise e confirmação pela empresa.' },
      },
      construtoras: {
        headline: 'Uma página coerente com a oferta real da construtora.',
        intro: 'Uma página para contratar construção tem requisitos diferentes de uma página para vender unidades próprias. O diagnóstico confirma a oferta e ajuda a organizar conteúdo e contato para cada jornada.',
        pain: 'Uma apresentação institucional ampla pode deixar o visitante sem saber se a empresa recebe pedidos de obra ou vende um empreendimento específico.',
        focus: ['Objetivo confirmado para a página.', 'Evidências técnicas ou informações do produto conforme a oferta.', 'Destino específico para cada tipo de solicitação.'],
        faq: { question: 'Posso apresentar obras e imóveis na mesma página?', answer: 'É possível apresentar as duas atividades quando ambas existem, mas a jornada precisa ser clara. Para uma campanha específica, vale avaliar uma página dedicada ao objetivo que motivou o acesso.' },
      },
    },
  },
  {
    slug: 'trafego-pago-imobiliario',
    name: 'Tráfego pago imobiliário',
    keyword: 'tráfego pago imobiliário',
    shortName: 'Tráfego pago',
    eyebrow: 'Mídia e atendimento',
    headline: 'Tráfego pago imobiliário começa com oferta, destino e capacidade de atendimento.',
    intro: 'Anunciar exige mais que escolher uma plataforma: é preciso definir o que será divulgado, quem deve chegar e como o contato será conduzido. Comece pelo diagnóstico atual da Imobiturbo para avaliar essas condições e discutir se a mídia é a prioridade da sua operação.',
    problem: 'Um anúncio pode gerar conversas que não avançam porque a oferta está pouco clara, a página não explica o produto ou o atendimento não registra o próximo passo. Olhar apenas cliques e formulários não revela se o gargalo está na campanha ou na condução comercial.',
    steps: [
      { title: 'Validar a oferta', text: 'Conferir disponibilidade, público, objetivo e informações autorizadas para os anúncios. Para empresas de obra, distinguir busca por contratantes de divulgação de produtos imobiliários.' },
      { title: 'Revisar o destino', text: 'Avaliar a coerência entre anúncio, página ou WhatsApp e perguntas de qualificação. Identificar quem atende e se há capacidade para acompanhar novas solicitações.' },
      { title: 'Discutir mídia e critérios', text: 'Avaliar canais, verba disponível, materiais e sinais que permitem acompanhar a jornada. Investimento em plataforma e eventuais serviços devem ser definidos separadamente no escopo.' },
      { title: 'Relacionar campanha e funil', text: 'Planejar como origem, perfil, atendimento e evolução comercial serão registrados. Essa leitura permite discutir ajustes sem atribuir toda dificuldade à mídia.' },
    ],
    deliverables: [
      'Leitura da oferta e da prontidão comercial para receber contatos.',
      'Hipóteses de canais e mensagens a avaliar conforme o público.',
      'Requisitos de criativos e informações autorizadas para divulgação.',
      'Revisão da jornada entre anúncio, destino e atendimento.',
      'Critérios para acompanhar origem, qualificação e avanço comercial.',
      'Pontos de decisão sobre verba, acessos e responsabilidades do projeto.',
    ],
    faq: [
      { question: 'Qual é o investimento necessário para anunciar?', answer: 'Depende do objetivo, público, canais e capacidade de atendimento. Não existe um valor único definido aqui. O diagnóstico considera a verba disponível e distingue investimento em mídia de qualquer serviço que venha a ser acordado.' },
      { question: 'O diagnóstico já inclui gestão de campanhas?', answer: 'Não automaticamente. A conversa inicial identifica a necessidade e permite discutir o escopo. Gestão recorrente, criação de anúncios, acompanhamento e acessos precisam ser confirmados antes de qualquer execução.' },
      { question: 'Tráfego pago garante vendas ou contatos qualificados?', answer: 'Não. Oferta, mercado, mensagem, qualificação e atendimento influenciam o resultado. A avaliação deve considerar o caminho até a conversa e a evolução comercial, sem promessa de custo, volume ou venda.' },
      { question: 'Preciso anunciar para começar o diagnóstico?', answer: 'Não. Acesse /#diagnostico com sua oferta e seu principal desafio. Se já anuncia, leve exemplos e informações de atendimento; se ainda não anuncia, a conversa ajuda a avaliar as condições para começar.' },
    ],
    profiles: {
      corretores: {
        headline: 'Mídia para o corretor com oferta definida e tempo para atender.',
        intro: 'O diagnóstico considera o imóvel ou nicho divulgado, a disponibilidade da carteira e a rotina de resposta. A campanha precisa caber na capacidade de acompanhar as oportunidades.',
        pain: 'Conversas novas competem com visitas e negociações, enquanto anúncios de imóveis já indisponíveis continuam atraindo interessados.',
        focus: ['Oferta atual e autorização para anunciar.', 'Destino que explique o imóvel e facilite a conversa.', 'Agenda de resposta e registro dos retornos.'],
        faq: { question: 'Devo anunciar toda a minha carteira?', answer: 'A prioridade depende da oferta, do público e da capacidade de acompanhamento. Leve os imóveis disponíveis ao diagnóstico para discutir um recorte antes de distribuir esforço entre várias campanhas.' },
      },
      imobiliarias: {
        headline: 'Tráfego para a imobiliária com distribuição e leitura das oportunidades.',
        intro: 'A campanha precisa se conectar à carteira e ao atendimento do time. O diagnóstico examina como cada contato recebe um responsável e como o gestor acompanha sua evolução.',
        pain: 'O volume de formulários parece positivo, mas contatos duplicados, demora de resposta e falta de registro impedem avaliar as oportunidades.',
        focus: ['Objetivos separados por carteira e tipo de demanda.', 'Regras de distribuição e responsabilidade comercial.', 'Leitura de origem, qualificação e andamento do atendimento.'],
        faq: { question: 'Como comparar campanhas se cada corretor registra de um jeito?', answer: 'É necessário discutir critérios comuns de registro e avanço no funil. Sem essa base, a comparação fica limitada a dados de plataforma e não mostra o que aconteceu no atendimento.' },
      },
      incorporadoras: {
        headline: 'Mídia para o empreendimento alinhada à fase de venda e aos canais.',
        intro: 'Campanhas de uma incorporadora devem considerar produto, fase comercial e rede de parceiros. O diagnóstico avalia a mensagem atual e como o interesse chega à operação responsável.',
        pain: 'Anúncios e parceiros podem disputar contatos sem uma leitura comum de origem, disponibilidade e estágio do comprador.',
        focus: ['Objetivo de campanha conforme a fase do empreendimento.', 'Criativos e condições aprovados para divulgação.', 'Relação entre canais próprios, parceiros e atendimento.'],
        faq: { question: 'A mesma campanha serve para lançamento e estoque remanescente?', answer: 'Esses momentos podem exigir mensagens e prioridades diferentes. O diagnóstico considera as unidades disponíveis, as dúvidas dos compradores e os canais ativos para discutir a adequação da campanha.' },
      },
      empreiteiras: {
        headline: 'Mídia para contratação de obras e demandas B2B compatíveis.',
        intro: 'A oferta de uma empreiteira deve alcançar quem contrata execução de obra ou procura parceiros técnicos. Antes de anunciar, o diagnóstico verifica especialidades, capacidade e área de atendimento informada pela empresa.',
        pain: 'Anúncios genéricos de imóveis atraem compradores que não procuram execução de obra, enquanto pedidos técnicos chegam sem informações para avaliação.',
        focus: ['Perfil de contratantes e parceiros desejados.', 'Serviço de obra e limites de atendimento confirmados.', 'Qualificação por escopo, localização e fase do projeto.'],
        faq: { question: 'Preciso usar anúncios de imóveis para captar obras?', answer: 'Não. A mensagem deve apresentar a execução de obra e orientar uma conversa de contratação. Divulgação de imóveis só faz sentido se existir um produto autorizado para comercialização.' },
      },
      construtoras: {
        headline: 'Tráfego para a construtora conforme a oferta que será anunciada.',
        intro: 'A mídia pode ter como objetivo pedidos de obra ou interesse em produtos próprios, quando existentes. O diagnóstico valida essa oferta antes de definir público, mensagem e destino.',
        pain: 'Uma campanha que mistura construção sob contrato e venda de unidades recebe demandas com critérios de qualificação incompatíveis.',
        focus: ['Confirmação do modelo comercial da campanha.', 'Destino dedicado à obra ou ao produto próprio.', 'Critérios técnicos ou comerciais de qualificação.'],
        faq: { question: 'Posso anunciar unidades se a construtora apenas executa a obra?', answer: 'É preciso confirmar quem comercializa o produto e a autorização de divulgação. Executar uma obra não significa ter unidades à venda; o diagnóstico deve esclarecer a responsabilidade comercial.' },
      },
    },
  },
  {
    slug: 'social-media-imobiliario',
    name: 'Social media imobiliário',
    keyword: 'social media imobiliário',
    shortName: 'Social media',
    eyebrow: 'Conteúdo e relacionamento',
    headline: 'Social media imobiliário com temas que ajudam seu público a decidir.',
    intro: 'Uma presença nas redes precisa explicar a atuação, responder dúvidas e orientar uma conversa relevante. Use o diagnóstico atual da Imobiturbo para relacionar conteúdo, oferta e rotina comercial antes de discutir produção ou gestão de perfis.',
    problem: 'Um perfil formado apenas por anúncios de imóveis ou publicações genéricas pode deixar dúvidas sobre a atuação da empresa. Sem uma pauta ligada ao público e uma rotina de resposta, comentários e mensagens não encontram continuidade no atendimento.',
    steps: [
      { title: 'Definir público e papel do perfil', text: 'Identificar quem precisa entender a oferta e quais dúvidas antecedem a decisão. Distinguir relacionamento com compradores, proprietários, parceiros e contratantes de obras.' },
      { title: 'Organizar linhas de conteúdo', text: 'Relacionar informações de produto, orientação e evidências verificáveis. Definir quais assuntos dependem de autorização ou atualização antes de serem publicados.' },
      { title: 'Planejar uma rotina viável', text: 'Avaliar disponibilidade de materiais, pessoas e tempo para revisão e resposta. Frequência e formatos devem acompanhar a capacidade real da operação.' },
      { title: 'Conectar conteúdo e conversa', text: 'Definir chamadas para ação e encaminhamento de comentários e mensagens. Discutir produção, publicação e acompanhamento somente após confirmar as responsabilidades do escopo.' },
    ],
    deliverables: [
      'Leitura do posicionamento e das dúvidas do público nas redes.',
      'Linhas editoriais vinculadas às ofertas e à atuação confirmada.',
      'Inventário de materiais disponíveis e autorizações de uso.',
      'Critérios de pauta, revisão e atualização das informações.',
      'Orientações de chamada para ação e encaminhamento de mensagens.',
      'Prioridades de formatos e rotina a avaliar conforme a capacidade da equipe.',
    ],
    faq: [
      { question: 'Social media imobiliário é só publicar imóveis?', answer: 'O conteúdo também pode explicar a atuação, responder dúvidas e apresentar informações que ajudem na decisão. A pauta depende do público: um comprador de imóvel, um proprietário e um contratante de obra procuram respostas diferentes.' },
      { question: 'A Imobiturbo já inclui produção e postagem diária?', answer: 'Produção, revisão, publicação e resposta a mensagens precisam de escopo e responsáveis definidos. O diagnóstico é a etapa para entender a necessidade e discutir um formato viável, sem presumir gestão diária incluída.' },
      { question: 'Preciso publicar todos os dias?', answer: 'A frequência deve considerar materiais, disponibilidade e capacidade de manter informações corretas. Uma rotina que a equipe consegue sustentar permite planejar melhor a pauta e dar continuidade às conversas.' },
      { question: 'Como avaliar se o conteúdo ajuda a operação?', answer: 'Observe quais dúvidas aparecem, que tipo de conversa o conteúdo inicia e como essas solicitações avançam. Leve exemplos ao diagnóstico para discutir critérios de acompanhamento além de curtidas e seguidores.' },
    ],
    profiles: {
      corretores: {
        headline: 'Conteúdo para tornar clara a atuação do corretor.',
        intro: 'A pauta pode combinar informações da carteira, dúvidas de compra e explicações sobre o atendimento. O diagnóstico ajuda a selecionar temas que o corretor consegue produzir e acompanhar na rotina.',
        pain: 'Copiar tendências sem relação com a carteira consome tempo e não esclarece para quem o corretor trabalha nem como pode ajudar.',
        focus: ['Recorte de atuação e dúvidas recorrentes dos clientes.', 'Apresentação de imóveis com informações atualizadas.', 'Chamadas para conversa e rotina de resposta.'],
        faq: { question: 'Preciso aparecer em todos os vídeos?', answer: 'O formato depende dos materiais e da disponibilidade. Imagens autorizadas, explicações e respostas às dúvidas também podem compor a pauta; a escolha deve preservar clareza e viabilidade de produção.' },
      },
      imobiliarias: {
        headline: 'Conteúdo de marca conectado à carteira e à equipe da imobiliária.',
        intro: 'O perfil institucional pode orientar compradores e proprietários sem perder coerência com a divulgação dos corretores. O diagnóstico considera quem fornece materiais, revisa e responde.',
        pain: 'Publicações feitas por várias pessoas podem trazer informações divergentes, enquanto comentários ficam sem um responsável claro.',
        focus: ['Pautas distintas para compradores e proprietários.', 'Critérios comuns para divulgar carteira e atuação da equipe.', 'Responsabilidades de aprovação e atendimento nas redes.'],
        faq: { question: 'O perfil da imobiliária deve repetir o conteúdo dos corretores?', answer: 'O perfil institucional pode apresentar a marca, a carteira e orientações de atendimento, enquanto cada corretor trabalha seu recorte. A pauta deve discutir como essas presenças se complementam.' },
      },
      incorporadoras: {
        headline: 'Conteúdo para explicar o empreendimento ao longo da comercialização.',
        intro: 'A pauta deve acompanhar as informações aprovadas sobre o produto e sua fase. O diagnóstico avalia como apresentar conceito, tipologias e dúvidas de compra com consistência entre marca e parceiros.',
        pain: 'Imagens de apresentação, informações de obra e condições comerciais sem contexto podem gerar interpretações erradas sobre o estágio do empreendimento.',
        focus: ['Conteúdo compatível com a fase e o material aprovado.', 'Explicação das características e dúvidas do produto.', 'Alinhamento das informações compartilhadas com parceiros.'],
        faq: { question: 'Posso usar imagens ilustrativas do empreendimento?', answer: 'O uso depende de autorização e identificação clara do que é ilustrativo. Informações, imagens e condições precisam de revisão pela operação responsável antes da publicação.' },
      },
      empreiteiras: {
        headline: 'Conteúdo técnico para apresentar a atuação da empreiteira.',
        intro: 'A pauta pode explicar especialidades, etapas de trabalho e requisitos para avaliar uma obra. Registros autorizados ajudam contratantes e parceiros B2B a compreender a capacidade da empresa.',
        pain: 'Um perfil sem contexto técnico pode mostrar obras sem explicar o papel da empreiteira, o serviço executado ou o tipo de contrato que ela procura.',
        focus: ['Especialidades e papel real na execução de obras.', 'Registros autorizados com contexto técnico verificável.', 'Orientação para pedidos de proposta e parcerias B2B.'],
        faq: { question: 'Posso publicar fotos de obras de clientes?', answer: 'É necessário verificar autorização de uso e o que pode ser exposto. A publicação deve explicar a participação da empreiteira e preservar informações do cliente que não estejam liberadas.' },
      },
      construtoras: {
        headline: 'Conteúdo que esclareça o papel da construtora em cada projeto.',
        intro: 'A pauta deve distinguir capacidade de execução de obra e divulgação de produtos próprios, quando confirmados. O diagnóstico define quais públicos e ofertas o perfil precisa atender.',
        pain: 'Fotos de projetos sem explicar a responsabilidade da empresa podem fazer o público presumir que ela incorpora, vende ou executa etapas que não fazem parte da sua atuação.',
        focus: ['Identificação do papel da empresa em cada projeto.', 'Pautas específicas para contratantes ou compradores.', 'Revisão técnica e comercial das informações publicadas.'],
        faq: { question: 'Mostrar uma obra significa divulgar um imóvel à venda?', answer: 'Não. O conteúdo pode apresentar capacidade construtiva, com autorização e contexto. Para divulgar venda, é necessário confirmar produto, disponibilidade e responsabilidade pela comercialização.' },
      },
    },
  },
];
