// Render editable HTML from one offer shared with the landing and subscription page.
const fs = require('node:fs');
const path = require('node:path');
const offer = require('./offer.js');
const base = '/os-crm/v2/';
const asset = name => `${base}assets/${name}`;
const logo = `<img class="logo" src="${asset('logo-os.webp')}" width="2048" height="550" alt="Imobiturbo OS">`;
const icon = (name, alt = '', extra = '') => `<img class="brand-icon ${extra}" src="${asset(`icons/${name}.svg`)}" width="28" height="28" alt="${alt}" loading="lazy">`;
const metaBadge = `<div class="meta-partner-badge"><img src="${asset('logo-meta.svg')}" alt="Meta" width="15" height="10"><span>Meta Technology Partner</span></div>`;
const loopVideo = (name, label, id = '') => `<video ${id ? `id="${id}"` : ''} data-loop-video autoplay loop muted playsinline preload="none" poster="${asset(`${name}-poster.webp`)}" width="1920" height="1080" aria-label="${label}"><source data-src="${asset(`${name}.webm`)}" type="video/webm"><source data-src="${asset(`${name}.mp4`)}" type="video/mp4"></video>`;
const uiIcon = paths => `<svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths}</svg>`;
const closeIcon = uiIcon('<path d="m6 6 12 12M18 6 6 18"/>');
const proofControls = `<div class="proof-controls" hidden><div class="proof-seek-wrap"><input class="proof-seek" type="range" min="0" max="100" step="0.1" value="0" data-proof-seek aria-label="Posição do vídeo" disabled></div><div class="proof-controls-row"><button class="proof-button proof-play-button" type="button" data-proof-toggle aria-label="Reproduzir vídeo" title="Reproduzir vídeo"><span data-icon-play>${uiIcon('<path d="m9 5 11 7-11 7Z" fill="currentColor" stroke="none"/>')}</span><span data-icon-pause hidden>${uiIcon('<path d="M8 5v14M16 5v14" stroke-width="3"/>')}</span></button><output class="proof-time" data-proof-time aria-label="Tempo de reprodução">0:00 <span>/ 0:00</span></output><div class="proof-controls-spacer"></div><button class="proof-button" type="button" data-proof-mute aria-label="Silenciar vídeo" title="Silenciar vídeo"><span data-icon-sound>${uiIcon('<path d="m11 5-6 4H2v6h3l6 4ZM15 8a6 6 0 0 1 0 8M18 5a10 10 0 0 1 0 14"/>')}</span><span data-icon-muted hidden>${uiIcon('<path d="m11 5-6 4H2v6h3l6 4ZM17 9l5 6M22 9l-5 6"/>')}</span></button><button class="proof-button" type="button" data-proof-fullscreen aria-label="Tela cheia" title="Tela cheia">${uiIcon('<path d="M8 3H3v5M16 3h5v5M3 16v5h5M21 16v5h-5"/>')}</button></div></div>`;
const cta = (text = 'Quero meu WhatsApp vendendo', href = '#planos', extra = '') => `<a class="cta ${extra}" href="${href}">${text}</a>`;
const section = (id, content, extra = '') => `<section id="${id}" class="section ${extra}"><div class="wrap">${content}</div></section>`;
const head = (title, desc, eyebrow = '') => `<div class="section-head reveal">${eyebrow ? `<div class="eyebrow">${eyebrow}</div>` : ''}<h2>${title}</h2>${desc ? `<p>${desc}</p>` : ''}</div>`;
const bar = label => `<div class="window-bar"><i></i><i></i><i></i><span>${label}</span></div>`;
const chat = `<div class="mini-window motion-chat" data-motion-demo="chat" aria-label="Exemplo animado de qualificação no WhatsApp">${bar('WhatsApp · atendimento IA')}<div class="chat-stream-viewport"><div class="chat-stream"><div class="motion-bubble buyer"><div class="chat-sender">${icon('whatsapp')}Comprador (WhatsApp)</div><p>Vi o anúncio da cobertura. Ainda está disponível?</p></div><div class="motion-bubble assistant"><div class="chat-sender"><span class="ai-badge">IA</span> Assistente Imobiturbo</div><p>Sim! Você procura para morar ou investir? E qual orçamento tem em mente?</p></div></div></div></div>`;
const miniKanban = `<div class="mini-window motion-kanban" data-motion-demo="kanban" aria-label="Exemplo animado de lead avançando no CRM">${bar('Imobiturbo OS · funil de vendas')}<div class="kanban-concept">${['Novos','Visitas','Proposta'].map((stage,i) => `<div class="motion-col ${i === 0 ? 'active' : ''}" data-motion-stage="${i}"><div class="motion-col-head"><b>${stage}</b><span data-motion-count>${i === 0 ? 1 : 0}</span></div><div class="motion-slot" ${i === 0 ? 'hidden' : ''}>Aguardando</div>${i === 0 ? `<div class="motion-lead"><strong>Carlos M.</strong><span class="motion-status">Novo lead</span><small>(21) 98765-4321</small><b>Cobertura · R$ 420 mil</b><span class="motion-origin">Meta Lead Ads</span><em data-motion-note>Interesse em compra à vista</em><div class="motion-detail">IA iniciando atendimento</div></div>` : ''}</div>`).join('')}</div></div>`;
const featureData = [
  ['Organize suas negociações no CRM', 'Cada negócio em uma coluna visual. Da primeira mensagem à proposta, seu funil avança e nenhum follow-up decisivo fica para depois.', miniKanban],
  ['Qualifique compradores com IA', 'Seu melhor plantonista trabalha 24h por dia. Levanta o interesse, identifica o perfil de compra e passa a conversa para você entrar na negociação.', chat],
  ['Inbox: todo atendimento em um só lugar', 'Chega de caçar conversas em cinco celulares. Centralize os números da operação, acompanhe o histórico e assuma a conversa na hora de fechar.', `<div class="agent-row">${icon('whatsapp')}<div>Todos os seus WhatsApps<br><small class="muted">Uma única Inbox</small></div><span class="badge live">Online</span></div><div class="agent-row"><span class="avatar">AR</span><div>Ana · Corretora<br><small class="muted">Camila · visita confirmada</small></div></div><div class="agent-row"><span class="avatar">JS</span><div>João · Corretor<br><small class="muted">André · proposta em análise</small></div></div>`],
  ['Follow-up: o dinheiro está no retorno', 'O cliente sumiu? O OS continua o acompanhamento. Configure suas cadências e faça a próxima mensagem acontecer sem depender da sua memória.', `<div class="timeline"><div class="timeline-line"><b>D+1</b><div>Retomar a conversa<small>Olá! Ficou alguma dúvida sobre o imóvel?</small></div></div><div class="timeline-line"><b>D+3</b><div>Reaquecer o interesse<small>Enviar material e próximos passos.</small></div></div><div class="timeline-line"><b>D+7</b><div>Trazer o cliente de volta<small>Convidar para conhecer o imóvel.</small></div></div></div>`],
  ['Roleta: lead certo, corretor certo', 'Distribua as oportunidades por regras da equipe. Organize responsáveis, evite disputa por atendimento e acompanhe quem está fazendo o lead avançar.', `<div class="team-lead">Novo lead qualificado pela IA</div><div class="team-dots"><span class="avatar">AR</span><span class="avatar">JS</span><span class="avatar">LC</span></div><div class="team-lead"><span class="accent">✓</span> Encaminhado ao próximo corretor</div>`],
];
const features = featureData.map(([title, copy, visual]) => `<article class="feature reveal"><div class="feature-visual">${visual}</div><div class="feature-copy"><h3>${title}</h3><p>${copy}</p></div></article>`).join('\n');
const proofs = [
  ['Joyce', 'O 1º lead virou venda.<br>R$ 67 mil de comissão.', 'joyce.jpg', 'f2538eec-287b-468b-87e1-925bbe5a976a', '0:42'],
  ['Joan', 'R$ 5 milhões em VGV.<br>R$ 155 mil de comissão.', 'joan.jpg', '242739f2-81f6-45d3-a215-a148a1de3f3b', '0:47'],
  ['Kelly Matias', 'R$ 5 mil investidos.<br>R$ 40 mil de comissão.', 'kelly.jpg', '76f71fa2-79c4-4667-802b-bcea4b509696', '0:53'],
].map(([name, title, image, id, duration]) => `<a class="proof-card reveal" href="${asset(image.replace('.jpg','.mp4'))}" data-proof="${image.replace('.jpg','.mp4')}" data-proof-name="${name}" aria-label="Assistir ao relato de ${name}"><div class="proof-thumb"><img src="${asset(image)}" alt="${name} em seu depoimento" loading="lazy" width="640" height="360"><span class="proof-play"><b aria-hidden="true">▶</b>Assistir ao relato · ${duration}</span></div><div class="proof-copy"><h3>${title}</h3><p>${name} · Cliente Imobiturbo</p></div></a>`).join('\n');
const before = ['Você compra o lead. O concorrente responde primeiro.', 'Cliente pedindo informação e conversa esquecida no WhatsApp.', 'O funil depende da sua memória e de planilhas atrasadas.', 'Você visita um imóvel e o atendimento da operação para.', 'Leads disputados, sem responsável e sem acompanhamento.', 'No fim do dia: muito esforço, pouca clareza do que virou visita.'];
const after = ['A IA responde em 3 segundos e mantém o cliente na conversa.', 'WhatsApps, histórico e equipe reunidos em uma única Inbox.', 'Cada oportunidade com etapa, responsável e próximo passo.', 'Atendimento 24h por dia. Você pode focar na negociação.', 'Distribuição de leads e cadências conforme as regras da equipe.', 'Você enxerga a operação e entra onde pode acelerar a venda.'];
const comparison = (items, extra, label, title) => `<article class="compare-card reveal ${extra}"><div class="label">${label}</div><h3>${title}</h3><ul>${items.map(text => `<li>${text}</li>`).join('')}</ul></article>`;
const leadData = [
  ['Camila Duarte', 'Casa · 180 m²', 'Facebook Lead Ads', 'R$ 510.000', 'AR', true],
  ['André Ribeiro', 'Apartamento · 2 dorm.', 'WhatsApp', 'R$ 495.000', 'JS', false],
  ['Larissa Nunes', 'Apartamento · 3 dorm.', 'Site', 'R$ 570.000', 'LC', false],
  ['Juliana Santos', 'Casa · 3 dorm.', 'Indicação', 'R$ 540.000', 'AR', false],
];
const leadCard = (data, canMove = false) => `<article class="board-lead ${data[5] ? 'highlight' : ''}" data-demo-lead data-owner="${data[4]}"><h5>${data[0]}</h5><div class="value">${data[3]}</div><p>${data[1]}</p><p>${data[2]}</p><div class="lead-footer"><span class="avatar">${data[4]}</span>Equipe Demonstração</div>${canMove ? '<div class="board-actions"><button type="button" data-move-lead>Avançar para visita →</button></div>' : ''}</article>`;
const board = `<div class="product-frame wide-frame reveal">${bar('Imobiturbo OS · CRM Kanban')}<div class="crm-board"><div class="board-top"><h3>Funil de vendas</h3><div class="board-filter" aria-label="Filtrar a demonstração"><button type="button" data-board-filter="all" aria-pressed="true">Todos</button><button type="button" data-board-filter="AR" aria-pressed="false">Ana · Corretora</button></div></div><div class="board-columns"><div class="board-col"><h4>Novo lead <span data-stage-count>1</span></h4>${leadCard(leadData[1])}</div><div class="board-col"><h4>Qualificar <span data-stage-count>2</span></h4>${leadCard(leadData[0], true)}${leadCard(leadData[2])}</div><div class="board-col" data-visit-column><h4>Visita agendada <span data-stage-count>1</span></h4>${leadCard(leadData[3])}</div><div class="board-col"><h4>Proposta <span data-stage-count>0</span></h4><p class="small">Seu próximo fechamento começa no primeiro atendimento.</p></div></div></div><p class="frame-note" aria-live="polite" id="board-feedback">Demonstração com dados ilustrativos. Experimente filtrar a equipe e avançar o lead.</p></div>`;
const plansHTML = Object.entries(offer.plans).map(([key, p]) => {
  const price = offer.price(key, 'annual');
  return `<article class="plan-card reveal ${key === 'growth' ? 'popular' : ''}" data-plan="${key}"><div class="plan-top"><h3>${p.name}</h3>${key === 'growth' ? '<span class="badge">Mais escolhido</span>' : ''}</div><p>${p.audience}</p><div class="plan-price" data-plan-price>${price.headline}</div><div class="plan-period" data-plan-period>${price.period}</div><div class="plan-detail" data-plan-detail>${price.detail}</div>${cta(`Quero meu OS ${p.name}`, offer.checkoutURL(key, 'annual'), key === 'growth' ? '' : 'ghost')}<ul>${p.features.map(text => `<li>${text}</li>`).join('')}</ul></article>`;
}).join('\n');
const faqs = [
  ['O que o Imobiturbo OS faz por mim?', 'O OS reúne WhatsApp, atendimento da equipe, IA, CRM Kanban e follow-up. O lead entra, a IA atende e qualifica, a oportunidade ganha um responsável e você acompanha cada próximo passo até a negociação.'],
  ['Eu trabalho sozinho. O OS serve para mim?', 'Sim. O Start foi pensado para o corretor solo: 1 conexão de WhatsApp, 1 usuário e a base completa de IA, Inbox e Kanban. A operação cresce? Você pode escolher Growth ou Scale.'],
  ['A IA vai saber responder sobre os meus imóveis?', 'Você configura a base de conhecimento, materiais e instruções da sua operação. A IA usa esse contexto no atendimento e pode transferir a conversa para um corretor. Você mantém o controle do que ela deve dizer e fazer.'],
  ['Posso assumir a conversa quando quiser?', 'Sim. A Inbox reúne as conversas e o histórico para sua equipe acompanhar o atendimento e assumir quando a negociação pede um corretor. A IA ajuda a manter o plantão funcionando.'],
  ['Como conecto meu WhatsApp?', 'Você conecta seu número no OS e configura sua operação. O onboarding foi pensado para começar em 15 minutos; acesso, conexão e materiais da IA precisam estar prontos. As opções de conexão dependem do canal escolhido.'],
  ['O cliente que sumiu recebe follow-up?', 'Você pode configurar fluxos de acompanhamento, prazos e mensagens para retomar o contato. O OS organiza o processo e respeita as regras de pausa, transferência e encerramento definidas pela sua operação.'],
  ['Funciona no celular e no computador?', 'Sim. Acesse pelo navegador no computador ou no celular para acompanhar o funil, o atendimento e os leads da operação.'],
  ['Quais são as integrações?', 'WhatsApp é o centro do atendimento. Meta Lead Ads, portais imobiliários, seu site e importação de leads ajudam a trazer oportunidades e conectar a operação. Importe sua base de planilhas por CSV. A disponibilidade e os limites variam conforme o plano.'],
  ['Qual a diferença entre mensal e anual?', 'No mensal, você paga por mês e pode cancelar quando quiser. No anual, a oferta tem valor à vista ou 12 parcelas. Os dois totais estão informados nos planos e na seleção da assinatura.'],
  ['Preciso de mais números ou mais corretores?', 'A oferta atual prevê conexão extra de WhatsApp por R$ 49,90/mês e usuário corretor extra por R$ 29,90/mês. Confirme os adicionais na contratação.'],
  ['Como contrato e recebo meu acesso?', 'Escolha seu plano e ciclo. A página da assinatura apresenta o resumo e abre o WhatsApp da equipe Imobiturbo para orientar a contratação e o acesso. Quem já tem matrícula pode seguir para o acesso de aluno.'],
  ['Tenho garantia?', 'A oferta anual tem garantia incondicional de 7 dias, conforme os termos da contratação. A assinatura mensal pode ser cancelada quando quiser.'],
];
const navLinks = `<a href="#produto">Produto</a><a href="#ia">Inteligência artificial</a><a href="#integracoes">Integrações</a><a href="#planos">Planos</a><a href="#faq">FAQ</a>`;
const docHead = (title, description, checkout = false) => `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><meta http-equiv="Content-Security-Policy" content="default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'; media-src 'self' blob:; connect-src 'self'; frame-src 'none'; object-src 'none'; base-uri 'self'; form-action 'none'"><title>${title}</title><meta name="description" content="${description}"><meta name="theme-color" content="#050505"><meta property="og:title" content="${title}"><meta property="og:description" content="${description}"><meta property="og:image" content="https://www.imobiturbo.com.br${asset('hero-current-desktop.webp')}"><meta property="og:type" content="website"><link rel="icon" href="/favicon.svg"><link rel="preload" href="${asset('PlusJakartaSans-latin.woff2')}" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="${asset('os.css')}">${checkout ? `<link rel="stylesheet" href="${base}assinatura/checkout.css">` : `<link rel="preload" href="${asset('hero-current-desktop.webp')}" as="image" media="(min-width:768px)"><link rel="preload" href="${asset('hero-current-mobile-phone.webp')}" as="image" media="(max-width:767px)">`}<script src="${base}offer.js" defer></script>${checkout ? '' : `<script src="${base}proof-player.js" defer></script>`}<script src="${base}${checkout ? 'assinatura/checkout.js' : 'lp.js'}" defer></script></head>`;
const html = `${docHead('Imobiturbo OS — Seu WhatsApp atendendo e vendendo 24h', 'Responda seus leads em 3 segundos. IA no WhatsApp, CRM Kanban, follow-up e equipe em uma só operação. Conheça o Imobiturbo OS.')}<body>
<a class="skip" href="#conteudo">Pular para o conteúdo</a>
<header class="nav"><div class="nav-inner"><a href="#inicio" aria-label="Imobiturbo OS — início">${logo}</a><nav class="nav-links" aria-label="Navegação principal">${navLinks}</nav><div class="nav-actions"><a class="nav-login" href="https://os.imobiturbo.com.br/login">Já tenho acesso</a>${cta('Quero meu OS')}</div></div></header>
<main id="conteudo" class="page-surface">
<section id="inicio" class="hero"><div class="hero-art" aria-hidden="true"><video class="hero-video hero-video-desktop" data-loop-video autoplay loop muted playsinline preload="none" poster="${asset('hero-current-desktop.webp')}" width="1920" height="1080" tabindex="-1"><source data-src="${asset('hero-current-desktop.mp4')}" type="video/mp4"></video><video class="hero-video hero-video-mobile" data-loop-video autoplay loop muted playsinline preload="none" poster="${asset('hero-current-mobile-phone.webp')}" width="1080" height="1920" tabindex="-1"><source data-src="${asset('hero-current-mobile-phone.mp4')}" type="video/mp4"></video></div><div class="hero-shade" aria-hidden="true"></div><div class="hero-copy"><img class="hero-mobile-logo" src="${asset('logo-os.webp')}" alt="Imobiturbo OS" width="2048" height="550"><div class="hero-endorsement">${metaBadge}</div><h1>Atenda em <span class="accent">3 segundos.</span><br>Venda sem deixar nenhum lead para trás.</h1><p>Enquanto você visita um imóvel, o OS responde, qualifica e mantém o cliente na conversa. <strong>Seu WhatsApp trabalha 24h por dia. Você entra para fechar.</strong></p><div class="hero-actions">${cta()}${cta('Ver o OS em ação', '#demo', 'ghost')}</div><div class="hero-proof"><div><b>3s</b><span>Resposta imediata</span></div><div><b>24h</b><span>IA no plantão</span></div><div><b>15min</b><span>Para começar</span></div></div><div class="hero-notice">Para corretores solo, imobiliárias e equipes de vendas.</div></div></section>
${section('produto', head('SEU LEAD CHEGOU.<br><span class="accent">A IA JÁ RESPONDEU.</span><br>E o concorrente?', 'Chega de pagar por oportunidade e perder a venda no atendimento. O Imobiturbo OS coloca WhatsApp, IA, funil e equipe para trabalhar juntos.') + `<div class="feature-grid">${features}</div><div class="motion-note"><span>Demonstrações com dados ilustrativos.</span><button type="button" data-toggle-motion aria-pressed="false">Pausar animações</button></div>`, 'glow')}
${section('demo', head('CRM para organizar contatos.<br><span class="accent">E fazer cada negócio avançar.</span>', 'Acompanhe cada cliente, visita e proposta no Imobiturbo OS. Centralize o atendimento e os próximos retornos. Sua oportunidade não pode ficar perdida no WhatsApp.', 'Seu funil trabalhando pela venda') + `<div class="demo-tabs" role="tablist" aria-label="Demonstração do OS"><button type="button" id="tab-crm" role="tab" aria-selected="true" aria-controls="demo-panel" data-demo="crm">CRM no computador</button><button type="button" id="tab-whatsapp" role="tab" aria-selected="false" aria-controls="demo-panel" data-demo="whatsapp" tabindex="-1">IA no WhatsApp</button></div><div class="crm-showcase"><div class="demo-frame reveal" id="demo-panel" role="tabpanel" aria-labelledby="tab-crm">${loopVideo('os-macbook-real', 'Demonstração do CRM Imobiturbo OS no computador', 'os-demo')}</div><ol class="annotations reveal"><li><span class="annotation-number">01</span><div><h3 data-demo-heading="0">Veja cada negociação por etapa</h3><p data-demo-copy="0">Novos, qualificados, visitas e propostas. Arraste o card e faça cada oportunidade avançar sem complicação.</p></div></li><li><span class="annotation-number">02</span><div><h3 data-demo-heading="1">Saiba quando retomar cada contato</h3><p data-demo-copy="1">Histórico da conversa e próximos retornos no mesmo lugar. Nunca mais deixe um cliente qualificado esfriar por esquecimento.</p></div></li><li><span class="annotation-number">03</span><div><h3 data-demo-heading="2">Chegue à negociação com contexto</h3><p data-demo-copy="2">Orçamento, interesse, urgência e notas antes do primeiro áudio. Você entra na conversa sabendo o que o cliente quer.</p></div></li></ol></div><p class="demo-caption">Demonstração do produto com dados ilustrativos.</p><div class="center-cta">${cta('Quero essa operação para mim')}</div>`, 'compact glow')}
${section('resultados', head('Quem transforma atendimento<br>em venda <span class="accent">tem história para contar.</span>', 'Corretores que aplicam o Imobiturbo e contam seus resultados com a própria voz.') + `<div class="proof-grid">${proofs}</div><p class="proof-context">Relatos de clientes do ecossistema Imobiturbo. Conheça o contexto de cada resultado nos vídeos.</p>`, 'light testimonials')}
${section('diferenciais', head('Um lead. Uma conversa.<br><span class="accent">Uma operação inteira trabalhando.</span>', 'O OS conecta as três peças que não podem falhar entre o anúncio e a venda.') + `<div class="pillar-grid"><article class="pillar reveal"><div class="num">01 / ATENDIMENTO</div><h3>Velocidade para<br>ganhar a conversa.</h3><p>WhatsApp com IA no plantão. O cliente recebe atenção enquanto o interesse ainda está quente.</p></article><article class="pillar reveal"><div class="num">02 / PROCESSO</div><h3>Clareza para<br>fazer o lead avançar.</h3><p>Kanban, responsável, histórico e follow-up. Você sabe quem precisa de ação e qual é a próxima.</p></article><article class="pillar reveal"><div class="num">03 / EQUIPE</div><h3>Controle para<br>acelerar os corretores.</h3><p>Distribuição e visão da operação. O lead deixa de ficar perdido entre números, celulares e pessoas.</p></article></div><div class="outcome reveal"><span>DO WHATSAPP À NEGOCIAÇÃO</span><strong>IA atende. OS organiza. Você fecha.</strong></div><p class="manifesto-line">Seu CRM precisa trabalhar pela venda.<br>Não virar mais uma tarefa para o corretor.</p>`, 'light pillars')}
${section('antes-depois', head('O que muda quando<br><span class="accent">seu WhatsApp ganha um OS.</span>', '') + `<div class="comparison">${comparison(before, '', 'ANTES', 'Muito lead. Atendimento no improviso.')}${comparison(after, 'after', 'AGORA', 'Uma operação pronta para vender.')}</div><div class="center-cta">${cta('Quero parar de perder oportunidades')}</div>`)}
${section('integracoes', head('Seus leads vêm de vários lugares.<br><span class="accent">Sua operação é uma só.</span>', 'Conecte a entrada de oportunidades ao atendimento. Pare de copiar dados e começar cada conversa do zero.') + `<div class="integration-orbit reveal"><svg class="orbit-lines" viewBox="0 0 920 460" aria-hidden="true"><ellipse cx="460" cy="230" rx="360" ry="155"/><ellipse cx="460" cy="230" rx="180" ry="215"/><path d="M110 90 460 230 810 90M110 370 460 230 810 370M460 20V440"/></svg><div class="integration-center">${logo}</div><div class="integration-node">${icon('whatsapp')}<span>WhatsApp</span></div><div class="integration-node">${icon('meta')}<span>Meta Lead Ads</span></div><div class="integration-node">${icon('portais')}<span>Portais Imobiliários</span></div><div class="integration-node">${icon('excel', 'Microsoft Excel')}<span>Importe seus Leads</span></div><div class="integration-node">${icon('site')}<span>Seu site</span></div><div class="integration-node">${icon('openai')}<span>Assistentes de IA</span></div></div><p class="integration-note">As integrações e os limites disponíveis dependem do plano e da configuração dos seus canais.</p>`)}
${section('crm', head('Todo lead visível.<br><span class="accent">Toda oportunidade com direção.</span>', 'Troque o “depois eu vejo” por um funil claro. Saiba quem acabou de chegar, quem está qualificado, quem vai visitar e quem já está negociando.') + board + `<p class="crm-note">A melhor oportunidade do dia não pode ficar enterrada em uma conversa.</p>`)}
${section('inbox', `<div class="split"><div class="reveal"><div class="eyebrow">Inbox para vender em equipe</div><h2>Você entra na conversa.<br><span class="accent">O histórico já está lá.</span></h2><p>Um cliente não pode repetir tudo só porque mudou de corretor. Reúna os números da operação, acompanhe a IA e assuma o atendimento com o contexto na mão.</p><div class="tags"><span>MÚLTIPLOS NÚMEROS</span><span>HISTÓRICO</span><span>RESPONSÁVEL</span><span>ATENDIMENTO HUMANO</span></div></div><div class="product-frame reveal">${bar('Imobiturbo OS · Inbox')}<div class="chat-demo"><div class="agent-row"><span class="avatar">CD</span><div>Camila Duarte<br><small class="muted">Qualificada · Visita agendada</small></div><span class="badge">Ana</span></div><div class="bubble">Amanhã às 15h fica ótimo.</div><div class="bubble ai">Combinado! Vou avisar a corretora para confirmar sua visita.<small>Assistente IA ✓✓</small></div><div class="bubble ai">Oi, Camila! Sou a Ana. Vou te acompanhar na visita.<small>Corretora Ana ✓✓</small></div></div><p class="frame-note">Exemplo de atendimento com dados ilustrativos.</p></div></div>`, 'compact')}
${section('ia', `<div class="whatsapp-showcase"><div class="whatsapp-copy reveal"><div class="eyebrow">Inteligência artificial no WhatsApp</div><h2>IA no WhatsApp para <span class="accent">atender e qualificar compradores 24h.</span></h2><p>A IA faz o atendimento inicial e identifica o perfil do comprador. Você acompanha as conversas no CRM e assume a negociação.</p><div class="responsibilities"><article><img src="${asset('emoji-apple-robot.png')}" width="32" height="32" alt="" loading="lazy"><h3>Atendimento inicial com IA</h3><p>Responde a qualquer hora, levanta orçamento e confirma o interesse. Seu conhecimento e seus imóveis no atendimento.</p></article><article><img src="${asset('emoji-apple-corretor.png')}" width="32" height="32" alt="" loading="lazy"><h3>Você entra para fechar</h3><p>O cliente já chega com contexto. Você conduz a visita, apresenta o imóvel e avança para a proposta.</p></article></div></div><div class="conversation-panel reveal"><h3>Demonstração de atendimento e qualificação</h3><div class="whatsapp-video">${loopVideo('wa-agenda-real', 'Demonstração de atendimento e agendamento com IA no WhatsApp')}</div><p>Da primeira resposta à visita agendada: o atendimento continua enquanto você negocia.</p></div></div><div class="center-cta">${cta('Quero a IA no meu plantão')}</div>`, 'compact')}
${section('followup', `<div class="split"><div class="reveal"><div class="eyebrow">Follow-up automático</div><h2>O cliente sumiu.<br><span class="accent">Sua oportunidade, não.</span></h2><p>Boa parte das vendas começa no retorno que ninguém fez. Configure as cadências da sua operação e mantenha o acompanhamento de quem ainda não decidiu.</p><p>Depois da visita, depois da proposta, depois do silêncio: <strong>o próximo contato deixa de depender da sua memória.</strong></p><div class="tags"><span>CADÊNCIAS</span><span>PRÓXIMO CONTATO</span><span>PAUSA E TRANSFERÊNCIA</span></div></div><div class="product-frame reveal">${bar('Imobiturbo OS · fluxos de acompanhamento')}<img src="${asset('followup-current.webp')}" alt="Editor atual de cadências do Imobiturbo OS, com etapas de espera, mensagens com IA e regras de acompanhamento" loading="lazy" width="3360" height="2048"><p class="frame-note">Editor atual de acompanhamento. Cadência de demonstração com mensagens por IA.</p></div></div>`, 'compact')}
${section('operacao', head('Mais que responder rápido.<br><span class="accent">Controle para vender melhor.</span>', 'O atendimento começa no WhatsApp. A gestão continua em toda a operação.') + `<div class="overview-grid">${[
  ['01', 'Distribuição de leads', 'Regras claras para encaminhar oportunidades. Cada corretor sabe quais atendimentos são seus.'],
  ['02', 'Desempenho da equipe', 'Acompanhe o andamento do funil e encontre o ponto em que suas oportunidades estão parando.'],
  ['03', 'Operação no celular', 'Acompanhe sua operação no escritório, no plantão ou entre uma visita e outra.'],
  ['04', 'Múltiplos funis', 'Organize compra, locação e captação sem misturar processos que precisam de cuidados diferentes.'],
  ['05', 'Sua base organizada', 'Contatos, contexto e histórico no mesmo lugar. Você não começa o relacionamento do zero.'],
  ['06', 'Você no comando', 'Defina o jeito de atender, o conhecimento da IA e quando sua equipe assume a conversa.'],
].map(([n,t,p]) => `<article class="overview-card reveal"><div class="overview-icon">${n}</div><h3>${t}</h3><p>${p}</p></article>`).join('')}</div><div class="center-cta">${cta('Quero o controle da minha operação')}</div>`, 'glow')}
${section('apoio', head('Suporte para usar a plataforma: <span class="accent">IA 24h e equipe em horário comercial.</span>', 'Consulte guias de configuração e tire dúvidas de uso com o suporte por IA a qualquer hora. Conte também com a equipe humana em horário comercial.', 'Acompanhamento e suporte contínuo') + `<div class="support-panel reveal"><div class="support-example"><div class="support-bubble"><strong>Dúvida comum de quem começa:</strong><p>“Como preparo a IA para responder sobre meus imóveis?”</p></div><div class="support-bubble tinted"><strong>Orientação do suporte IA:</strong><p>“Reúna os materiais dos imóveis, condições e perguntas frequentes. Adicione esse conteúdo à base de conhecimento do seu assistente e defina as instruções de atendimento. Depois, teste uma conversa e ajuste as respostas antes de ativar o atendimento.”</p></div><p class="support-note">Suporte técnico com inteligência artificial disponível 24 horas por dia.</p></div><div class="support-guide"><img src="${asset('emoji-apple-open-book.png')}" width="32" height="32" alt="" loading="lazy"><h3>Tutoriais e Guias Passo a Passo</h3><p>Instruções visuais para conectar o WhatsApp, configurar o CRM e colocar sua operação para trabalhar.</p><div class="support-guide-media">${loopVideo('loop-help-center', 'Guia visual de configuração e suporte do Imobiturbo OS')}</div></div></div><div class="center-cta">${cta('Quero começar com suporte')}</div>`, 'compact')}
${section('criador', `<p class="authority-quote reveal">“Corretor precisa estar na negociação.<br><span class="accent">Não preso ao celular o dia inteiro.</span>”</p><div class="authority-grid"><img class="authority-image reveal" src="${asset('natan.webp')}" alt="Natan Pimentel ensinando atendimento e processo de vendas imobiliárias" loading="lazy" width="1086" height="1448"><div class="authority-copy reveal"><div class="eyebrow">Criado dentro do Imobiturbo</div><h2>Natan Pimentel,<br><span class="accent">criador do Imobiturbo.</span></h2><p>Quem trabalha com corretor vê a mesma cena se repetir: o lead chega, a rotina aperta e a oportunidade esfria antes de virar conversa.</p><p>Um anúncio pode trazer o contato. Mas é o atendimento, o acompanhamento e o processo que fazem esse contato avançar.</p><p>O OS reúne essas peças. É tecnologia a serviço do que importa na operação imobiliária: <strong>atender melhor, gerar mais visitas e chegar à negociação com o cliente certo.</strong></p><div class="signature">@natanpimentels · Imobiturbo</div></div></div>`)}
${section('planos', head('Uma venda pode mudar seu mês.<br><span class="accent">Comece pela sua operação.</span>', 'Escolha o plano para o seu momento. Corretor solo ou equipe: seu WhatsApp já pode trabalhar com o OS.') + `<div class="billing-toggle" aria-label="Ciclo de contratação"><button type="button" data-cycle="monthly" aria-pressed="false">Mensal</button><button type="button" data-cycle="annual" aria-pressed="true">Anual · melhor condição</button></div><div class="plan-grid">${plansHTML}</div><p class="offer-notes">Conexão extra de WhatsApp: R$ 49,90/mês · Usuário corretor extra: R$ 29,90/mês.<br>Mensal sem fidelidade. No anual, confira os valores à vista e parcelados antes de contratar.</p><div class="guarantee"><b>7 dias</b><span><strong>Garantia incondicional na oferta anual.</strong><br>Você tem 7 dias para decidir, conforme os termos da contratação.</span></div>`, 'compact')}
${section('faq', `<div class="faq-grid"><div class="faq-intro reveal"><h2>Perguntas<br><span class="accent">frequentes.</span></h2><p>O que você precisa saber para colocar seu WhatsApp e seu funil para trabalhar.</p></div><div class="faq-list reveal">${faqs.map(([q,a], i) => `<details ${i === 0 ? 'open' : ''}><summary>${q}</summary><p>${a}</p></details>`).join('\n')}</div></div>`, 'compact')}
${section('comece', `<div class="final-panel reveal"><div class="eyebrow">O próximo lead pode chegar agora</div><h2>Mais uma oportunidade.<br><span class="accent">Ou mais uma conversa perdida?</span></h2><p>Seu concorrente não vai esperar você organizar o WhatsApp. Coloque o OS para atender, acompanhar e fazer cada lead avançar.</p>${cta('Quero começar com o Imobiturbo OS')}</div>`, 'compact')}
</main>
<footer class="footer"><div class="footer-giant" aria-hidden="true">IMOBITURBO</div><div class="footer-marquee" aria-hidden="true"><div>${Array(4).fill('<span>IA no WhatsApp <b>✦</b></span><span>CRM imobiliário <b>✦</b></span><span>Follow-up automático <b>✦</b></span><span>Equipe organizada <b>✦</b></span><span>Você entra para fechar <b>✦</b></span>').join('')}</div></div><div class="footer-main"><h2>Pronto para colocar seu WhatsApp para vender?</h2>${cta()}<nav class="nav-links" aria-label="Navegação do rodapé">${navLinks}</nav></div><div class="footer-bottom"><div class="footer-brand">${logo}<p>© 2026 Imobiturbo</p></div><img class="meta-partner-seal" alt="Meta Technology Partner" width="105" height="59" loading="lazy" src="${asset('selo-meta-partner.svg')}"><div class="legal-links"><a href="/termos-de-servico/">Termos de serviço</a><a href="/politica-de-privacidade/">Privacidade</a><a href="/exclusao-de-dados/">Exclusão de dados</a></div><button class="top-button" type="button" data-top aria-label="Voltar ao topo">↑</button></div></footer>
<dialog class="video-dialog" id="proof-dialog" aria-labelledby="proof-title"><div class="dialog-top"><div class="dialog-heading"><span class="dialog-eyebrow">Quem usa conta</span><span id="proof-title">Depoimento Imobiturbo</span></div><button class="proof-close" type="button" data-close-proof aria-label="Fechar vídeo"><span>Fechar</span>${closeIcon}</button></div><div class="proof-stage"><div id="proof-player"></div><p class="proof-status" data-proof-status role="status" hidden></p>${proofControls}</div></dialog>
</body></html>`;
const checkout = `${docHead('Sua assinatura — Imobiturbo OS', 'Escolha seu plano e coloque o Imobiturbo OS para trabalhar na sua operação.', true)}<body class="checkout-body">
<header class="checkout-header"><a href="${base}" aria-label="Voltar para a página do Imobiturbo OS">${logo}</a><a href="https://os.imobiturbo.com.br/login" class="checkout-login">Já tenho acesso →</a></header>
<main class="checkout-main"><div class="checkout-intro"><div class="eyebrow">Seu próximo passo</div><h1>Seu WhatsApp está prestes<br>a ganhar um <span class="accent">OS.</span></h1><p>Escolha o plano. Confira a oferta. Ative com a equipe Imobiturbo.</p></div><div class="checkout-layout">
<section class="checkout-panel" aria-label="Seleção da assinatura"><div class="checkout-panel-title"><span class="step-number">01</span><h2>Monte sua assinatura</h2></div><div class="billing-toggle"><button type="button" data-cycle="monthly" aria-pressed="false">Mensal</button><button type="button" data-cycle="annual" aria-pressed="true">Anual</button></div><fieldset class="checkout-plans"><legend class="sr-only">Escolha seu plano</legend>${Object.entries(offer.plans).map(([key,p]) => `<label class="checkout-plan"><input type="radio" name="plan" value="${key}" ${key === 'growth' ? 'checked' : ''}><span><b>${p.name}</b><small>${p.audience}</small></span><strong data-checkout-price="${key}">${offer.price(key, 'annual').headline}</strong></label>`).join('')}</fieldset><div class="checkout-benefits"><h3>O que está no seu plano</h3><ul id="checkout-features">${offer.plans.growth.features.map(f => `<li>${f}</li>`).join('')}</ul></div><a class="checkout-back" href="${base}#planos">← Voltar para comparar os planos</a></section>
<aside class="checkout-summary"><div class="checkout-summary-head"><span class="badge live">Imobiturbo OS</span><h2>Resumo da assinatura</h2></div><div class="summary-row"><span>Plano escolhido</span><b id="summary-plan">Growth</b></div><div class="summary-row"><span>Contratação</span><b id="summary-cycle">Anual</b></div><div class="summary-price" id="summary-price">12x R$ 177</div><p class="summary-price-detail" id="summary-detail">R$ 1.770 por ano à vista · ou R$ 2.124 em 12 parcelas</p><div class="summary-divider"></div><div class="activation-note"><span class="step-number">02</span><div><strong>Ative com a equipe Imobiturbo</strong><p>O próximo passo abre nosso WhatsApp com o plano escolhido. A equipe orienta a contratação e a liberação do acesso.</p></div></div><a class="cta" id="activate-os" href="${offer.activationURL('growth','annual')}" target="_blank" rel="noopener noreferrer">Solicitar minha ativação</a><p class="summary-fine">A seleção do plano não realiza cobrança.</p><div class="summary-guarantee" id="summary-guarantee"><span>✓</span><p>Garantia incondicional de 7 dias na oferta anual.</p></div><a id="existing-checkout" class="existing-access" href="${offer.existingAccessURL()}">Já sou aluno: acessar meu OS →</a></aside></div><div class="checkout-assurance"><span>✓ IA + CRM + WhatsApp</span><span>✓ Atendimento com a equipe</span><span>✓ Plano claro antes de contratar</span></div></main>
<footer class="checkout-footer"><span>© 2026 Imobiturbo</span><nav aria-label="Termos da contratação"><a href="/termos-de-servico/">Termos</a><a href="/politica-de-privacidade/">Privacidade</a></nav></footer>
</body></html>`;
function render(output = __dirname) {
  fs.mkdirSync(path.join(output, 'assinatura'), { recursive: true });
  fs.writeFileSync(path.join(output, 'index.html'), html);
  fs.writeFileSync(path.join(output, 'assinatura/index.html'), checkout);
}
if (require.main === module) render(process.argv[2]);
module.exports = { render };
